### PR TITLE
Add support for incremental annotation processing

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR adds incremental annotation processing support by updating `com.google.auto.service:auto-service` and adding the necessary `well-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors` file.

The tricky bit for enabling incremental annotation processing is not the work itself but rather making the correct category choice between `isolating`, `aggregating` & `dynamic` and making sure that our processors don't violate any of the rules for incremental annotation processing support. All of these are covered in [Gradle's Incremental annotation processing documentation](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing).

Even though I've completed this work a while back, I wanted to gain more confidence in the changes by running various tests in all 4 repositories Wellsql, FluxC, WPAndroid & WCAndroid. These tests were certainly helpful, but I still don't feel 100% confident mostly due to a lack of verifying changes - or rather the possibility of silent failures which is also mentioned in [Gradle's documentation](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing). I am hoping this is where the peer review will be _very_ helpful.

As a first step, I am opening draft PRs in Wellsql & [FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2452) repos so that we can discuss these changes. If everything looks good, I'll also open the PR in WPAndroid and once we verify everything works as expected, we can merge the PRs in and enable incremental annotation processing in Wellsql, FluxC, WPAndroid & WCAndroid repos.

**To test:**

Please follow the testing instructions in [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2452).

---

I strongly suggest going through the [Gradle documentation](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing) - possibly a few times - while reviewing these PRs. Here is my basic understanding of each category:

### Dynamic

> If your processor can only decide at runtime whether it is incremental or not, you can declare it as "dynamic" in the META-INF descriptor and return its true type at runtime using the [Processor#getSupportedOptions()](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html#getSupportedOptions--) method.

As far as I can tell, it a processor is not overriding the [Processor#getSupportedOptions()](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html#getSupportedOptions--) it won't need to be `dynamic` because that's where we tell whether we support incremental annotation processing or not, depending on some outside factors.

[Here is an example from Butterknife](https://github.com/JakeWharton/butterknife/blob/master/butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java) repository where `dynamic` category is used:

```
@Override public Set<String> getSupportedOptions() {
  ImmutableSet.Builder<String> builder = ImmutableSet.builder();
  builder.add(OPTION_SDK_INT, OPTION_DEBUGGABLE);
  if (trees != null) {
    builder.add(IncrementalAnnotationProcessorType.ISOLATING.getProcessorOption());
  }
  return builder.build();
}
```

As far as I can tell we don't have any processors that needs to be `dynamic`.

### Isolating

> The fastest category, these look at each annotated element in isolation, creating generated files or validation messages for it.

> They must make all decisions (code generation, validation messages) for an annotated type based on information reachable from its AST. This means you can analyze the types' super-class, method return types, annotations etc., even transitively. But you cannot make decisions based on unrelated elements in the RoundEnvironment. Doing so will result in silent failures because too few files will be recompiled later. If your processor needs to make decisions based on a combination of otherwise unrelated elements, mark it as "aggregating" instead.

> They must provide exactly one originating element for each file generated with the Filer API. If zero or many originating elements are provided, Gradle will recompile all source files.

Wellsql's [TableProcessor](https://github.com/wordpress-mobile/wellsql/blob/trunk/well-processor/src/main/java/com/yarolegovich/processor/TableProcessor.java) and FluxC's [ActionProcessor](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc-processor/src/main/java/org/wordpress/android/fluxc/processor/ActionProcessor.java) seems to fit this description. As far as I can tell, there is one originating source file in each case. [TableProcessor](https://github.com/wordpress-mobile/wellsql/blob/trunk/well-processor/src/main/java/com/yarolegovich/processor/TableProcessor.java) creates multiple files, `**Table.java` & `**Mapper.java`, but I don't think the number of generated files is a factor.

### Aggregating

> These can aggregate several source files into one or more output files or validation messages.

> "Aggregating" processors have the following limitations:

> * They can only read CLASS or RUNTIME retention annotations

> * They can only read parameter names if the user passes the -parameters compiler argument.

FluxC's [EndpointProcessor](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc-processor/src/main/java/org/wordpress/android/fluxc/processor/EndpointProcessor.java) seems to fit this description which processes multiple source files.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

FYI: I pushed a tmp commit to be able to test both `isolating` and `aggregating` versions of `TableProcessor` from the accompanying [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2452). I hope it is okay with you. 🙏 
```
wellSqlVersion = '21-4d9ded3274a8e1c6c236156cde1759047135e0bf' // com.yarolegovich.processor.TableProcessor,isolating
wellSqlVersion = '21-ab54ada07728e001d312c2802e7a6d49c90ee0c9' // com.yarolegovich.processor.TableProcessor,aggregating
```

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

FYI, that I unassigned myself from this PR, just so as to clean my GitHub related [assigned](https://github.com/pulls/assigned) list from having this PR there, and up until we get to work again on that again. I also removed the request for review on it for the same reason. 👍

**Comment by oguzkocer** [comment]
@ParaskP7 I experimented with enabling incremental annotation processing in WCAndroid a while back and I couldn't get any performance improvement out of it. Adding the fact that we have some issues with the current incremental annotation processing PRs and don't know exactly how to address them, I think it's best to close them for the moment.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

This makes sense to me, thanks for following-up on that, indeed, we can close them for the moment. 👍

**Pull request closed without merging**
