### PR TITLE
[Build] Upgrade Gradle to 8.2.1 and AGP to 8.0.2

### PR DESCRIPTION
**Pull request by ParaskP7**
Platform Request: `pdnsEh-13V-p2`
Project Thread: `paaHJt-57Z-p2`

This PR upgraded Gradle to [8.2.1](https://docs.gradle.org/8.2.1/release-notes.html) and AGP to [8.0.2](https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2).

FYI: The [8.1.1](https://docs.gradle.org/8.1.1/release-notes.html) Gradle upgrades had to happen in 2 parts (96baa77d79c6a64b44801f9336984ee911ffaa16 and 1260b8d86f4ae6879451cfa2a1f73cc6cd8196f7). This is because of the breaking changes that this upgrade introduces, including the `AGP` upgrade and its associated breaking changes (namespace, build option, etc).

PS: This Gradle and AGP upgrade was done in order to align this repo with the rest of such [WordPress-Mobile](https://github.com/wordpress-mobile) Android library related repos. However, mind the fact that this work here is not necessary to complete the aforementioned project, just some extra work to help with the wider alignment efforts.

-----

🚫 Blocked By:

- [ ] `Android Gradle plugin requires Java 17 to run. You are currently using Java 11.`

<details>
    <summary>CI Failure</summary>

```
[2023-07-17T13:57:38Z] FAILURE: Build failed with an exception.
--
  | [2023-07-17T13:57:38Z]
  | [2023-07-17T13:57:38Z] * Where:
  | [2023-07-17T13:57:38Z] Build file '/var/lib/buildkite-agent/builds/ci-android-i-0c1f8588a78c5ea3a-1/automattic/wellsql/well-sample/build.gradle' line: 2
  | [2023-07-17T13:57:38Z]
  | [2023-07-17T13:57:38Z] * What went wrong:
  | [2023-07-17T13:57:38Z] An exception occurred applying plugin request [id: 'com.android.application', version: '8.0.2']
  | [2023-07-17T13:57:38Z] > Failed to apply plugin 'com.android.internal.application'.
  | [2023-07-17T13:57:38Z]    > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
  | [2023-07-17T13:57:38Z]       Your current JDK is located in /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.x86_64
  | [2023-07-17T13:57:38Z]       You can try some of the following options:
  | [2023-07-17T13:57:38Z]        - changing the IDE settings.
  | [2023-07-17T13:57:38Z]        - changing the JAVA_HOME environment variable.
  | [2023-07-17T13:57:38Z]        - changing `org.gradle.java.home` in `gradle.properties`.
```

</details>

-----

Breaking Change List:

1. [Move package from android manifest to build files](https://github.com/wordpress-mobile/wellsql/commit/1eb6cb489f037c6f8915139aefe8c498d6181815)
2. [Use new publishing dsl to configure publication variants](https://github.com/wordpress-mobile/wellsql/commit/63c716a6dac263411729d0d95c22c753581769a4)

AGP Upgrade Assistant List:

1. [Remove ignored configuration properties](https://github.com/wordpress-mobile/wellsql/pull/25/commits/baf8f5dfc6ceb9043981924e33774d0ff363c1de)
2. [Migrate dsl properties from lint options to lint](https://github.com/wordpress-mobile/wellsql/pull/25/commits/b60a14563ca417cdf2cbf4053472c9851efa0968)

-----

## Associated clients (`N/A`)

FYI: `wellsql` is not part of a composite build, neither for `WPAndroid`, `WCAndroid` clients or the `FluxC` library.

-----

## To test:

- There is nothing much to test here (maybe that the `publishing` is still working as expected).
- Verifying that all the CI checks are successful should be enough.
- However, if you want to be thorough about reviewing this change, you could run `./gradlew build` locally and verify that  it is successful (see [previous](https://github.com/wordpress-mobile/wellsql/pull/24) such update).

-----

## Merge instructions

- [x] Mark PR as `Ready for review`.
- [x] Wait for PR to get approved.
- [x] Remove `[PR] Not Ready for Merge` label.
- [ ] In coordination with all the other library and client PRs, merge this PR only when every PR is ready to be merged. FYI: This is a nice to have step here, but not a necessary step per se since `wellsql` is not part of a composite build.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

I was just trying to figure out why the [Publish :wellsql](https://buildkite.com/automattic/wellsql/builds/27#018974a6-f68b-4bb9-bfe8-2892d20e291b) step was failing on CI and got the following:

```
[2023-07-20T19:02:33Z] > Task :wellsql:publishWellSqlPublicationPublicationToS3Repository FAILED
--
  | [2023-07-20T19:02:33Z]
  | [2023-07-20T19:02:33Z] FAILURE: Build failed with an exception.
  | [2023-07-20T19:02:33Z]
  | [2023-07-20T19:02:33Z] * What went wrong:
  | [2023-07-20T19:02:33Z] Execution failed for task ':wellsql:publishWellSqlPublicationPublicationToS3Repository'.
  | [2023-07-20T19:02:33Z] > Failed to publish publication 'WellSqlPublication' to repository 's3'
  | [2023-07-20T19:02:33Z]    > Invalid publication 'WellSqlPublication': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```

It seem that me adding [this commit](https://github.com/wordpress-mobile/wellsql/pull/25/commits/63c716a6dac263411729d0d95c22c753581769a4) was solving the `unknown property 'release'` build problem I was having, but still isn't enough. 😞 

Maybe your [publish-to-s3](https://github.com/Automattic/publish-to-s3-gradle-plugin/pull/31) work might do the trick here, that is, if we remove this configuration, or any outdated configuration for that matter, and use this newer, to be created `0.8.0` version of this [publish-to-s3-gradle-plugin](https://github.com/Automattic/publish-to-s3-gradle-plugin) library, wdyt? 🤔

**Review by oguzkocer — APPROVED** [review]
@ParaskP7 It looks like publish-to-s3 Gradle plugin update fixed the issue with publication. The changes look good to me, approving the PR pending testing.

**Comment by ParaskP7** [comment]
Awesome @oguzkocer , thanks for updating the `publish-to-s3` Gradle plugin, then reviewing and tentatively approving the changes, pending some extra testing! 🙇 ❤️ 🚀 

FYI: I went ahead, marked this PR as `Ready for review` and removed the `[PR] Not Ready for Merge` label. The last `nice to have` thing for us to do is to coordinate the merge wit with all the other library and client PRs, merging this PR only when every other such PR is ready to be merged as well.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

As per [this](https://github.com/Automattic/android-dependency-catalog/pull/20#issuecomment-1647430456) comment, I am now merging this `wellsql` update in order to then update that in the [catalog](https://github.com/Automattic/android-dependency-catalog) before cutting a new release.

**Pull request merged**
