### PR TITLE
Update Gradle and project dependencies

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR updates the Gradle version to `5.4.1` and some dependencies to make the build work. It also tries to update the `build.gradle` files to follow the https://docs.gradle.org/current/userguide/upgrading_version_5.html guide, but in a lot of cases it was just trial and error, so, it's hard to say if these are the correct set of changes or not. I am pretty sure there are at least a few more changes we could do to the build file, but I stopped once I had a successful build.

**_For context:_**
I am trying to update FluxC-Android project and I keep getting `com.yarolegovich.wellsql.core` package missing errors. I am not entirely sure if these changes are necessary for the resolution of that error. I've tried everything I could think of to fix that in the FluxC repo, but failed. I figured updating this library wouldn't hurt 🤞 even if it may not help.

@aforcier Can I bother you with a review?

To test:
* Run the sample app
* Run unit tests

### CODE REVIEW

**Comment by aforcier** [comment]
> I am trying to update FluxC-Android project and I keep getting com.yarolegovich.wellsql.core package missing errors. I am not entirely sure if these changes are necessary for the resolution of that error. I've tried everything I could think of to fix that in the FluxC repo, but failed. I figured updating this library wouldn't hurt 🤞 even if it may not help.

I'd need a testing branch in FluxC to test this, but I can at least confirm that these changes work in FluxC's current `develop`, so it's probably okay to update this regardless.

(Confirmed by building FluxC with this branch via the Jitpack method.)

I noticed that on the surface the connected tests seem to be failing:

```
$ ./gradlew cAT
...
> Task :wellsql:compileDebugAndroidTestJavaWithJavac FAILED
../wellsql/wellsql/src/androidTest/java/com/yarolegovich/wellsql/ApplicationTest.java:4: error: package android.test does not exist
import android.test.ApplicationTestCase;
                   ^
../wellsql/wellsql/src/androidTest/java/com/yarolegovich/wellsql/ApplicationTest.java:9: error: cannot find symbol
public class ApplicationTest extends ApplicationTestCase<Application> {
                                     ^
  symbol: class ApplicationTestCase
2 errors
```

The actual valuable tests are working fine though:

```
$ ./gradlew well-sample:connectedDebugAndroidTest
...
 V/InstrumentationResultParser: OK (27 tests)
```

Let's just delete `wellsql/src/androidTest/java/com/yarolegovich/wellsql/ApplicationTest.java` - I see you already deleted the one in `well-sample`.

**Comment by aforcier** [comment]
(:shipit: once `ApplicationTest` is deleted, confirmed that `./gradlew cAT` works without it - feel free to merge yourself @oguzkocer.)

**Comment by oguzkocer** [comment]
> Let's just delete `wellsql/src/androidTest/java/com/yarolegovich/wellsql/ApplicationTest.java` - I see you already deleted the one in `well-sample`.

Yes, I thought it was unnecessary and probably only added as part of creating the project. I did miss the other one though. I didn't think to run the `cAT` command, I'll keep it in mind going forward.

> (Confirmed by building FluxC with this branch via the Jitpack method.)

Do you mind sharing what you put into the build file for this? I have tried a couple different ways, one from README and one from the Jitpack itself and neither worked. Just had an idea while typing this, maybe we just don't have FluxC setup for Jitpack.

> (:shipit: once ApplicationTest is deleted, confirmed that ./gradlew cAT works without it - feel free to merge yourself @oguzkocer.)

`./gradlew cAT` failed a couple times for me, then it started working. Now it passes on both AS and command line, but because it failed a couple times, I'd really prefer if you could run it as well just to be on the safe side before merging it.

Thanks a lot for the detailed review, really appreciate it!

**Comment by aforcier** [comment]
> Do you mind sharing what you put into the build file for this? I have tried a couple different ways, one from README and one from the Jitpack itself and neither worked. Just had an idea while typing this, maybe we just don't have FluxC setup for Jitpack.

Might be the case - this is the diff I used that worked, I'm guessing you're missing the root `build.gradle` bit:

```diff
diff --git a/build.gradle b/build.gradle
index d27f3f664..2af483411 100644
--- a/build.gradle
+++ b/build.gradle
@@ -21,6 +21,7 @@ allprojects {
     repositories {
         google()
         jcenter()
+        maven { url "https://jitpack.io" }
     }
 
     task checkstyle(type: Checkstyle) {
diff --git a/fluxc/build.gradle b/fluxc/build.gradle
index 0f797000d..6881ba096 100644
--- a/fluxc/build.gradle
+++ b/fluxc/build.gradle
@@ -79,8 +79,8 @@ dependencies {
     }
 
     // Custom WellSql version
-    api "org.wordpress:wellsql:$wellSqlVersion"
-    kapt "org.wordpress:wellsql-processor:$wellSqlVersion"
+    api 'com.github.wordpress-mobile.wellsql:wellsql:5ee250c42e01e081270aa051fc8c9c9b7e737c07'
+    kapt 'com.github.wordpress-mobile.wellsql:well-processor:5ee250c42e01e081270aa051fc8c9c9b7e737c07'
 
     // FluxC annotations
     api project(':fluxc-annotations')
diff --git a/plugins/woocommerce/build.gradle b/plugins/woocommerce/build.gradle
index 97893f550..196b09bc9 100644
--- a/plugins/woocommerce/build.gradle
+++ b/plugins/woocommerce/build.gradle
@@ -52,8 +52,8 @@ dependencies {
         exclude group: "com.android.support"
     }
 
-    api "org.wordpress:wellsql:$wellSqlVersion"
-    kapt "org.wordpress:wellsql-processor:$wellSqlVersion"
+    api 'com.github.wordpress-mobile.wellsql:wellsql:5ee250c42e01e081270aa051fc8c9c9b7e737c07'
+    kapt 'com.github.wordpress-mobile.wellsql:well-processor:5ee250c42e01e081270aa051fc8c9c9b7e737c07'
 
     // FluxC annotations
     api project(':fluxc-annotations')
```

> ./gradlew cAT failed a couple times for me, then it started working. Now it passes on both AS and command line, but because it failed a couple times, I'd really prefer if you could run it as well just to be on the safe side before merging it.

Hmm it's working for me consistently in the command line, and I ran it once on AS earlier. And no issues running the tests from FluxC which is more important. I would maybe try to get it working in FluxC and confirm that the tests are running for you there, if they are :shipit:. WDYT?

**Comment by oguzkocer** [comment]
Thank you @aforcier! I was missing the `maven { url "https://jitpack.io" }` bit. I ran all the unit tests, some connected tests, did a clean rebuild and run the example app and everything worked OK. I think we are good to merge this.

For full disclosure: There was one timezone related unit test that failed for me, but it's completely unrelated to WellSql.

**Pull request merged**
